name: rocm-validation-suite
title: ROCm Validation Suite
license: MIT
version: 6.3.0
summary: A system validation and diagnostics tool for AMD GPUs
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by AMD.

  NOTE: Currently, the snap only works in `--devmode`. This is not recommended
  unless you know what you are doing. To learn more about the confinement
  levels, read https://snapcraft.io/docs/snap-confinement.

  The ROCm Validation Suite (RVS) is a system validation and diagnostics tool
  for monitoring, stress testing, detecting and troubleshooting issues that
  affects the functionality and performance of AMD GPU(s) operating in a
  high-performance/AI/ML computing environment. RVS is enabled using the ROCm
  software stack on a compatible software and hardware platform.

  RVS is a collection of tests, benchmarks and qualification tools each
  targeting a specific sub-system of the ROCm platform. All of the tools are
  implemented in software and share a common command line interface. Each set
  of tests are implemented in a "module" which is a library encapsulating the
  functionality specific to the tool. The CLI can specify the directory
  containing modules to use when searching for libraries to load. Each module
  may have a set of options that it defines and a configuration file that
  supports its execution.

website: https://rocm.docs.amd.com/projects/ROCmValidationSuite/en/latest/
contact: https://github.com/canonical/rocm-validation-suite-snap/issues
issues: https://github.com/canonical/rocm-validation-suite-snap/issues
source-code: https://github.com/ROCm/ROCmValidationSuite

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  rocm-validation-suite:
    command: opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/bin/rvs
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib
      PATH: $PATH:$SNAP/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/bin
    extensions: [gnome]
    plugs:
      - hardware-observe
      - home
      - network-bind
      - network-control
      - opengl
      - power-control
      - process-control
      - removable-media

package-repositories:
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/amdgpu/latest/ubuntu
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/rocm/apt/latest
    priority: 600

parts:
  rocm-validation-suite:
    plugin: cmake
    cmake-parameters:
      - -DROCM_PATH=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
      - -DCMAKE_INSTALL_PREFIX=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
      - -DCPACK_PACKAGING_INSTALL_PREFIX=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
    source: https://github.com/ROCm/ROCmValidationSuite.git
    source-type: git
    source-tag: rocm-${SNAPCRAFT_PROJECT_VERSION}
    build-snaps: [cmake]
    build-packages:
      - doxygen
      - hipblaslt-dev
      - hiprand-dev
      - libpci-dev
      - libpci3
      - libyaml-cpp-dev
      - rocblas-dev
      - rocm-dev
      - rocrand-dev
      - unzip
    stage-packages:
      - hipblaslt
      - hiprand
      - libyaml-cpp0.8
      - rocblas
      - rocm-smi-lib
      - rocrand
    stage:
      - -opt/amdgpu
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/libhiprtc.so*
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/liboam.so*
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/librocm-core.so*
      - -usr/include/ncursesw
      - -usr/lib/x86_64-linux-gnu/libform.so*
      - -usr/lib/x86_64-linux-gnu/libmenu.so*
      - -usr/lib/x86_64-linux-gnu/libncurses.so*
      - -usr/lib/x86_64-linux-gnu/libpanel.so*
