name: Check CLA

on:
  pull_request:
  merge_group:
    types: [checks_requested]

permissions: {}

jobs:
  cla-check:
    name: Check CLA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check if CLA is signed
        uses: canonical/has-signed-canonical-cla@1c20438ad54b4d37105e777000545881d2293ba4 # 2.2.0
